# Generated by Django 2.0.1 on 2018-01-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180121_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='locations',
            field=models.CharField(blank=True, default='my location default', max_length=120),
        ),
    ]
